---
- name: use 7 JDK version
  set_fact: jdk_version=7
  when: ansible_distribution_release in ["wheezy", "trusty"]
- name: use 8 JDK version
  set_fact: jdk_version=8
  when: ansible_distribution_release in ["jessie", "stretch"]
- name: use 9 JDK version
  set_fact: jdk_version=9
  when: ansible_distribution_release in ["xenial", "zesty", "artful", "bionic", "buster"]
- name: install openjdk
  apt: pkg='openjdk-{{ jdk_version }}-jdk'
