---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Create data dir
  file: path='{{ elasticsearch_data_path }}' state=directory owner=elasticsearch group=elasticsearch
  when: elasticsearch_data_path is defined

- name: list installed plugins
  command: /usr/share/elasticsearch/bin/plugin list
  register: es_plugins

- name: install ES plugins
  command: '/usr/share/elasticsearch/bin/plugin install {{ item }}'
  when: es_plugins.stdout.find('{{ item }}') == -1
  with_items: '{{ elasticsearch_plugins|default([]) }}'


- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: port={{ elasticsearch_http_port }} delay=3 timeout=300
